### ISSUE TITLE
Describe how to join

### ISSUE THREAD

**Issue by alansill** [gridcf/gridcf.github.io#7]
The site says "join us on GitHub" but I don't see how to ask to join. This should be described.

**Comment by fscheiner** [comment]
@alansill 
Oh, sorry, this issue got lost and I only (re)noticed it when I updated the news section of the GridCF site.

Checking the roster of our discuss@gridcf.org mailing list I see your email address listed, hence I assume the issue solved itself somehow in the meantime and this issue can be closed. Is that correct?

**Comment by alansill** [comment]
That works for the discussion list, assuming that information is now in the GitHub project description somewhere for others to find. Assume code contributions can be made in the usual way through pull requests.

**Comment by fscheiner** [comment]
> That works for the discussion list, assuming that information is now in the GitHub project description somewhere for others to find. Assume code contributions can be made in the usual way through pull requests.

That's correct: The information for joining our mailing lists is located below https://gridcf.org/#contact and code contributions work as usual via GitHub (i.e. via pull requests).
